# Lecture 48 and 49
#### the lecture was about data and its importance 
#### How to use numpy pandas matplotlib seaborn

# Lecture 50

# Numpy and Enviroment Setup


In [2]:
!pip install numpy

In [3]:
import numpy as np 
import time

In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)



(2, 3)
2
int64


In [5]:
py_list=list(range(1_000_000))
py_result=[]
start_time=time.time()
for i  in py_list:
    py_result.append(i+5)
end_time=time.time()
print(f"python  list time : {end_time-start_time}")

np_array=np.arange(1_000_000)
start_time=time.time()
np.result=np_array+5
end_time=time.time()
print("Numpy array time :",end_time-start_time)


python  list time : 0.9300956726074219
Numpy array time : 0.01007223129272461


This mean using  numpy is good for time and source

# Lecture 51
## creating Array in numpy

In [6]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [8]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [11]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [12]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [13]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [15]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
arr=np.array([1.5,2.7,244.4])
print(arr.astype(int))

[  1   2 244]


# Topic 52
## Numpy indexing slicing and strides

In [18]:
import numpy as np
arr=np.array([[10,20,30],
            [40,50,60],
            [70,80,90]])


In [ ]:
print(arr[0,1])# 20 will be printed
print(arr[2,2])# 90 will bw printed

20
90


In [20]:
# Negative indexing
print(arr[-1,-2])
print(arr[-3,-3])

80
10


In [22]:
#portion of array
#general form :arr[start,stop,step]
print(arr[0:2,1:3])


[[20 30]
 [50 60]]


In [23]:
print(arr[::2,::3])

[[10]
 [70]]


In [ ]:
slice_arr=arr[0,:2]#view (not copy)
slice_arr[0]=99


[99 20 30]


In [ ]:
print(arr[0])# original array change 

[99 20 30]


In [28]:
copy_arr=arr[1].copy()
copy_arr[0]=555


In [29]:
print(copy_arr[0])

555


In [30]:
print(arr[0])

[99 20 30]


# Lecture 53
### Numpy random numbers,reproducibilityand performance tips

In [3]:
import numpy as np 
import time

In [4]:
# Random number produces numbers randomly
#see_function use to generate random numbers from a specific distribution
rng=np.random.default_rng(seed=43)
flips=rng.integers(0,2,size=100000)
probs_heads=np.mean(flips)
print(f"estiamted probability of heads : {probs_heads}")


estiamted probability of heads : 0.50238


In [6]:
# python loop 
start=time.time()

square=[i**2 for i in range(100000)]
end=time.time()
print(f"Loop time: {end-start}")

Loop time: 0.03714919090270996


In [7]:
#Numpy vectorized operations
start=time.time()

arr=np.arange(100000)
sqr_np=arr**2
end=time.time()
print(f"Numpy Vectorized time : {end-start}")


Numpy Vectorized time : 0.004998207092285156
